name: Validate PR Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - '!dependabot**'

jobs:
  validate-pr-title:
    runs-on: ubuntu-20.04
    steps:
      - uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          regex: '^(fix|feat|refactor|chore|test)(\(MO-[0-9]+\))?(\[[0-9]+\])?: [A-Za-z0-9\,\;[\]\-_+. \/()]+$'
